# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# NeoForge Properties
minecraft_version=26.2
minecraft_version_range=[26.1.2,26.3)
neo_version=26.2.0.75
neo_version_range=[26.1.2.102,)

## Mod Properties
mod_id=fixescape
mod_name=FixEscape
mod_license=WTFPL
mod_version=1.2.0
mod_group_id=fr.oxodao.fixescape
mod_authors=Oxodao
mod_description=Make the game playable again for people using another key as escape
